### PR TITLE
Add react 18 as peer dependency to 16.9 and 17.

### PR DESCRIPTION
**Pull request by heller**
Hello, I hope this will remove the conflict when I try to use the editor with React 18. Thank you!

### CODE REVIEW

**Comment by heller** [comment]
Related to #270

**Comment by dmessing** [comment]
Love to see this get merged!

**Comment by MortensenC** [comment]
Please merge!

**Comment by vibbs** [comment]
@HarryChen0506 Any update on this merge? Anything pending on this one

**Comment by sylingd** [comment]
I will merge this PR and release a new version later. But I didn't test it, so there may be some bugs.

**Comment by Tasin5541** [comment]
> I will merge this PR and release a new version later. But I didn't test it, so there may be some bugs.

When will this get a release? V1.3.3 still has the old dependency.

**Comment by sylingd** [comment]
> > I will merge this PR and release a new version later. But I didn't test it, so there may be some bugs.
> 
> When will this get a release? V1.3.3 still has the old dependency.

v1.3.4 has released 4 months ago

**Pull request merged**
