### PR TITLE
Clarify the docs/api where I could

### PR DESCRIPTION
**Pull request by DAlperin**
Clarify the docs/API where it was ambiguous/had spelling errors etc. Fixes a spelling error in the syncScroll config object where it mispelled synchScroll. This is a breaking change.

### CODE REVIEW

**Comment by HarryChen0506** [comment]
That‘s great!  You helped me a lot in english writing，thank you very much again.  I will upgrade the next version (v0.5.0) recently, which aim to solve  breaking change and add a new feature about custom clear confirm dialog.

**Comment by DAlperin** [comment]
I can work on the custom dialog if you would like.

**Comment by DAlperin** [comment]
Oh! You beat me to it! Perfect :)

**Comment by HarryChen0506** [comment]
I think you can help us do better，so would you like to join us ? :-)

**Comment by DAlperin** [comment]
Definitely! I already have some bug fixes I'm working on.

**Pull request merged**
