### PR TITLE
Added loggerInterval and maxLogSize to logger plugin options

### PR DESCRIPTION
**Pull request by atsushifujikawa**
Added `loggerInterval` and `maxLogSize` to logger plugin options.
This may solve the problem of #188

#### Usage
```typescript
import MdEditor, { Plugins } from 'react-markdown-editor-lite';
MdEditor.use(Plugins.Logger, {
  loggerInterval: 100,
  maxLogSize: 200,
});
```

### CODE REVIEW

**Comment by atsushifujikawa** [comment]
@HarryChen0506 Could you please review this PR?

**Comment by atsushifujikawa** [comment]
@sylingd @HarryChen0506
I would like to have these changes merged if possible, is there anything I can do?

**Review by HarryChen0506 — APPROVED** [review]

**Comment by atsushifujikawa** [comment]
@sylingd 
Yes.
I would like to adjust the granularity of log data by changing the loggerInterval
In my case, by shortening the loggerInterval, I want to reduce the number of characters to be undone when Command+Z is pressed.
Also, when I set the loggerInterval short, the log data chunks increase and the speed of reaching maxLogSize also increases, so I want to increase maxLogSize so that I do not run out of logs.

**Comment by crtan7** [comment]
> @sylingd Yes. I would like to adjust the granularity of log data by changing the loggerInterval In my case, by shortening the loggerInterval, I want to reduce the number of characters to be undone when Command+Z is pressed. Also, when I set the loggerInterval short, the log data chunks increase and the speed of reaching maxLogSize also increases, so I want to increase maxLogSize so that I do not run out of logs.

Has it been updated, why did my configuration not take effect?

**Comment by crtan7** [comment]
> Has it been updated, why did my configuration not take effect?

Has it been updated, why did my configuration not take effect?

**Pull request merged**
