### PR TITLE
#83 Expose keydown function of editor to user

### PR DESCRIPTION
**Pull request by aitayn**
Expose keydown function of editor to user for adding any validation while typing.

### CODE REVIEW

**Comment by aitayn** [comment]
@sylingd / @HarryChen0506 Can you please review and merge the Request

**Comment by sylingd** [comment]
I don't want to add more props to editor, I will add onKeyDown as an event in editor's API.
Consider using editor's API

**Comment by aitayn** [comment]
That will also work. Please add it as event in editor's API

**Comment by aitayn** [comment]
@sylingd When can I expect it to be added in editor's API?

**Comment by sylingd** [comment]
Added

**Comment by HarryChen0506** [comment]
v1.0.1 has been released :-)

**Pull request closed without merging**
